# -*- coding: utf-8 -*-
"""geopy_example.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sRHCmOjxrkK8cte_k4-pZ8o4VXD84DmZ
"""

import numpy as np
import pandas as pd
from numpy import nan as NA
import geopy
from geopy.geocoders import Nominatim
geolocator = Nominatim(user_agent="geoapiExercises")
      
#Source:  https://www.geeksforgeeks.org/get-the-city-state-and-country-names-from-latitude-and-longitude-using-python/

# Specific latitude & Longitude input
Latitude = "38.89482116666670" #Note must be string
Longitude = "-77.04658983333330"

location = geolocator.reverse(Latitude+","+Longitude) 

print(location) #Works great
address = location.raw['address']
state = address.get('state', '')
print(state)

##Now try to apply to a DF
start_lat= [38.905737, 38.89482116666670, 38.915246, 38.8840581]
start_lng =[-77.02227, -77.04658983333330,-77.220157,-76.9863852]

df = pd.DataFrame(list(zip(start_lat, start_lng)),
               columns =['start_lat', 'start_lng'])
df
df['start_lat']=df['start_lat'].astype(str)
df['start_lat']=df['start_lat'].astype(str)

df['location2']=geolocator.reverse(df['start_lat']+","+df['start_lng'])
print(df['location2'])

